#!/usr/bin/env bash

FILE="$1"

while IFS= read -r NUM; do
    factors=($(factor "$NUM" 2>/dev/null))
    if [ ${#factors[@]} -ge 2 ]; then
        echo "$NUM=${factors[2]}*${factors[1]}"
    fi
done < "$FILE"

